# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20160611_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
